// Last Generated: 2011-08-25T23:29:48-04:00
package com.shopify.api.resources;

import java.io.ByteArrayOutputStream;
import java.io.FileDescriptor;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;

import com.apache.commons.codec.binary.Base64OutputStream;
import com.apache.commons.codec.binary.StringUtils;

/**
* This code has been machine generated by processing the single entry
* fixtures found from the Shopify API Documentation
*/
  
public class Image extends MGImage {
	private static final String FILENAME = "filename";
	private static final String ATTACHMENT = "attachment";
	
	public void setImage(InputStream image) {
		ByteArrayOutputStream base64bytes = new ByteArrayOutputStream();
		Base64OutputStream output = new Base64OutputStream(base64bytes, true, 80, new byte[] {});
		byte[] buffer = new byte[0x4000];
		int bytesRead = 0;
		try {
			while( (bytesRead = image.read(buffer, 0, buffer.length)) > 0) {
				output.write(buffer, 0, bytesRead);
			}
		} catch (IOException e) {
			
		}
		
		setAttribute(ATTACHMENT, StringUtils.newStringUsAscii(base64bytes.toByteArray()));
	}
	
	public void setFilename(String filename) {
		setAttribute(FILENAME, filename);
	}
	
	public void getFilename() { getAttribute(FILENAME); }
	
}