/**
 * DO NOT MODIFY THIS CODE
 *
 * Place all of your changes in Article.java
 *
 * It has been machine generated from fixtures and your changes will be
 * lost if anything new needs to be added to the API.
 **/
// Last Generated: 2011-09-26T15:53:49-04:00
package com.shopify.api.resources;

import java.util.List;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * This code has been machine generated by processing the single entry
 * fixtures found from the Shopify API Documentation
 */

public class MGArticle extends ShopifyResource {

	@JsonProperty("author")
	public String getAuthor() {
		return (String)getAttribute("author");
	}
	@JsonProperty("author")
	public void setAuthor(String _author) {
		setAttribute("author", _author);
	}

	@JsonProperty("blog_id")
	public int getBlogId() {
		Integer value = (Integer)getAttribute("blog_id");
		return value != null ? value : 0;
	}
	@JsonProperty("blog_id")
	public void setBlogId(int _blog_id) {
		setAttribute("blog_id", _blog_id);
	}

	@JsonProperty("body_html")
	public String getBodyHtml() {
		return (String)getAttribute("body_html");
	}
	@JsonProperty("body_html")
	public void setBodyHtml(String _body_html) {
		setAttribute("body_html", _body_html);
	}

	@JsonProperty("published_at")
	public String getPublishedAt() {
		return (String)getAttribute("published_at");
	}
	@JsonProperty("published_at")
	public void setPublishedAt(String _published_at) {
		setAttribute("published_at", _published_at);
	}

	@JsonProperty("summary_html")
	public String getSummaryHtml() {
		return (String)getAttribute("summary_html");
	}
	@JsonProperty("summary_html")
	public void setSummaryHtml(String _summary_html) {
		setAttribute("summary_html", _summary_html);
	}

	@JsonProperty("tags")
	public String getTags() {
		return (String)getAttribute("tags");
	}
	@JsonProperty("tags")
	public void setTags(String _tags) {
		setAttribute("tags", _tags);
	}

	@JsonProperty("title")
	public String getTitle() {
		return (String)getAttribute("title");
	}
	@JsonProperty("title")
	public void setTitle(String _title) {
		setAttribute("title", _title);
	}

	@JsonProperty("user_id")
	public int getUserId() {
		Integer value = (Integer)getAttribute("user_id");
		return value != null ? value : 0;
	}
	@JsonProperty("user_id")
	public void setUserId(int _user_id) {
		setAttribute("user_id", _user_id);
	}

}
