/**
* DO NOT MODIFY THIS CODE
* 
* Place all of your changes in Asset.java
* 
* It has been machine generated from fixtures and your changes will be
* lost if anything new needs to be added to the API. 
**/
// Last Generated: 2011-08-25T16:56:47-04:00
package com.shopify.api.resources;

import org.codehaus.jackson.annotate.JsonProperty;

/**
* This code has been machine generated by processing the single entry
* fixtures found from the Shopify API Documentation
*/
  
public class MGAsset extends ShopifyResource {

	@JsonProperty("public_url")
	private String _public_url;
	public String getPublic_url(){ return _public_url;}
	public void setPublic_url(String newpublic_url){_public_url = newpublic_url;}

	@JsonProperty("value")
	private String _value;
	public String getValue(){ return _value;}
	public void setValue(String newvalue){_value = newvalue;}

	@JsonProperty("key")
	private String _key;
	public String getKey(){ return _key;}
	public void setKey(String newkey){_key = newkey;}

}