/**
 * DO NOT MODIFY THIS CODE
 *
 * Place all of your changes in BillingAddress.java
 *
 * It has been machine generated from fixtures and your changes will be
 * lost if anything new needs to be added to the API. 
 **/
// Last Generated: 2011-08-31T09:06:23-04:00
package com.shopify.api.resources;

import java.util.List;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * This code has been machine generated by processing the single entry
 * fixtures found from the Shopify API Documentation
 */

public class MGBillingAddress extends ShopifyResource {

	@JsonProperty("company")
	private String _company;
	@JsonProperty("company")
	public String getCompany(){ return _company;}
	@JsonProperty("company")
	public void setCompany(String _company){this._company = _company;}

	@JsonProperty("city")
	private String _city;
	@JsonProperty("city")
	public String getCity(){ return _city;}
	@JsonProperty("city")
	public void setCity(String _city){this._city = _city;}

	@JsonProperty("address1")
	private String _address1;
	@JsonProperty("address1")
	public String getAddress1(){ return _address1;}
	@JsonProperty("address1")
	public void setAddress1(String _address1){this._address1 = _address1;}

	@JsonProperty("name")
	private String _name;
	@JsonProperty("name")
	public String getName(){ return _name;}
	@JsonProperty("name")
	public void setName(String _name){this._name = _name;}

	@JsonProperty("zip")
	private String _zip;
	@JsonProperty("zip")
	public String getZip(){ return _zip;}
	@JsonProperty("zip")
	public void setZip(String _zip){this._zip = _zip;}

	@JsonProperty("latitude")
	private String _latitude;
	@JsonProperty("latitude")
	public String getLatitude(){ return _latitude;}
	@JsonProperty("latitude")
	public void setLatitude(String _latitude){this._latitude = _latitude;}

	@JsonProperty("address2")
	private String _address2;
	@JsonProperty("address2")
	public String getAddress2(){ return _address2;}
	@JsonProperty("address2")
	public void setAddress2(String _address2){this._address2 = _address2;}

	@JsonProperty("country")
	private String _country;
	@JsonProperty("country")
	public String getCountry(){ return _country;}
	@JsonProperty("country")
	public void setCountry(String _country){this._country = _country;}

	@JsonProperty("country_code")
	private String _country_code;
	@JsonProperty("country_code")
	public String getCountryCode(){ return _country_code;}
	@JsonProperty("country_code")
	public void setCountryCode(String _country_code){this._country_code = _country_code;}

	@JsonProperty("province_code")
	private String _province_code;
	@JsonProperty("province_code")
	public String getProvinceCode(){ return _province_code;}
	@JsonProperty("province_code")
	public void setProvinceCode(String _province_code){this._province_code = _province_code;}

	@JsonProperty("phone")
	private String _phone;
	@JsonProperty("phone")
	public String getPhone(){ return _phone;}
	@JsonProperty("phone")
	public void setPhone(String _phone){this._phone = _phone;}

	@JsonProperty("last_name")
	private String _last_name;
	@JsonProperty("last_name")
	public String getLastName(){ return _last_name;}
	@JsonProperty("last_name")
	public void setLastName(String _last_name){this._last_name = _last_name;}

	@JsonProperty("longitude")
	private String _longitude;
	@JsonProperty("longitude")
	public String getLongitude(){ return _longitude;}
	@JsonProperty("longitude")
	public void setLongitude(String _longitude){this._longitude = _longitude;}

	@JsonProperty("province")
	private String _province;
	@JsonProperty("province")
	public String getProvince(){ return _province;}
	@JsonProperty("province")
	public void setProvince(String _province){this._province = _province;}

	@JsonProperty("first_name")
	private String _first_name;
	@JsonProperty("first_name")
	public String getFirstName(){ return _first_name;}
	@JsonProperty("first_name")
	public void setFirstName(String _first_name){this._first_name = _first_name;}

}