/**
* DO NOT MODIFY THIS CODE
* 
* Place all of your changes in Blog.java
* 
* It has been machine generated from fixtures and your changes will be
* lost if anything new needs to be added to the API. 
**/
// Last Generated: 2011-08-25T23:19:06-04:00
package com.shopify.api.resources;

import org.codehaus.jackson.annotate.JsonProperty;

/**
* This code has been machine generated by processing the single entry
* fixtures found from the Shopify API Documentation
*/
  
public class MGBlog extends ShopifyResource {

	@JsonProperty("handle")
	private String _handle;
	public String getHandle(){ return _handle;}
	public void setHandle(String _handle){_handle = this._handle;}

	@JsonProperty("template_suffix")
	private String _template_suffix;
	public String getTemplateSuffix(){ return _template_suffix;}
	public void setTemplateSuffix(String _template_suffix){_template_suffix = this._template_suffix;}

	@JsonProperty("title")
	private String _title;
	public String getTitle(){ return _title;}
	public void setTitle(String _title){_title = this._title;}

	@JsonProperty("feedburner_location")
	private String _feedburner_location;
	public String getFeedburnerLocation(){ return _feedburner_location;}
	public void setFeedburnerLocation(String _feedburner_location){_feedburner_location = this._feedburner_location;}

	@JsonProperty("feedburner")
	private String _feedburner;
	public String getFeedburner(){ return _feedburner;}
	public void setFeedburner(String _feedburner){_feedburner = this._feedburner;}

	@JsonProperty("commentable")
	private String _commentable;
	public String getCommentable(){ return _commentable;}
	public void setCommentable(String _commentable){_commentable = this._commentable;}

}