/**
 * DO NOT MODIFY THIS CODE
 *
 * Place all of your changes in Blog.java
 *
 * It has been machine generated from fixtures and your changes will be
 * lost if anything new needs to be added to the API.
 **/
// Last Generated: 2011-09-12T22:14:03-04:00
package com.shopify.api.resources;

import java.util.List;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * This code has been machine generated by processing the single entry
 * fixtures found from the Shopify API Documentation
 */

public class MGBlog extends ShopifyResource {

	@JsonProperty("handle")
	public String getHandle() {
		return (String)attributes.get("handle");
	}
	@JsonProperty("handle")
	public void setHandle(String _handle) {
		attributes.put("handle", _handle);
	}

	@JsonProperty("template_suffix")
	public String getTemplateSuffix() {
		return (String)attributes.get("template_suffix");
	}
	@JsonProperty("template_suffix")
	public void setTemplateSuffix(String _template_suffix) {
		attributes.put("template_suffix", _template_suffix);
	}

	@JsonProperty("title")
	public String getTitle() {
		return (String)attributes.get("title");
	}
	@JsonProperty("title")
	public void setTitle(String _title) {
		attributes.put("title", _title);
	}

	@JsonProperty("feedburner_location")
	public String getFeedburnerLocation() {
		return (String)attributes.get("feedburner_location");
	}
	@JsonProperty("feedburner_location")
	public void setFeedburnerLocation(String _feedburner_location) {
		attributes.put("feedburner_location", _feedburner_location);
	}

	@JsonProperty("feedburner")
	public String getFeedburner() {
		return (String)attributes.get("feedburner");
	}
	@JsonProperty("feedburner")
	public void setFeedburner(String _feedburner) {
		attributes.put("feedburner", _feedburner);
	}

	@JsonProperty("commentable")
	public String getCommentable() {
		return (String)attributes.get("commentable");
	}
	@JsonProperty("commentable")
	public void setCommentable(String _commentable) {
		attributes.put("commentable", _commentable);
	}

}
