/**
 * DO NOT MODIFY THIS CODE
 *
 * Place all of your changes in Comment.java
 *
 * It has been machine generated from fixtures and your changes will be
 * lost if anything new needs to be added to the API.
 **/
// Last Generated: 2011-09-12T22:14:03-04:00
package com.shopify.api.resources;

import java.util.List;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * This code has been machine generated by processing the single entry
 * fixtures found from the Shopify API Documentation
 */

public class MGComment extends ShopifyResource {

	@JsonProperty("body_html")
	public String getBodyHtml() {
		return (String)attributes.get("body_html");
	}
	@JsonProperty("body_html")
	public void setBodyHtml(String _body_html) {
		attributes.put("body_html", _body_html);
	}

	@JsonProperty("author")
	public String getAuthor() {
		return (String)attributes.get("author");
	}
	@JsonProperty("author")
	public void setAuthor(String _author) {
		attributes.put("author", _author);
	}

	@JsonProperty("body")
	public String getBody() {
		return (String)attributes.get("body");
	}
	@JsonProperty("body")
	public void setBody(String _body) {
		attributes.put("body", _body);
	}

	@JsonProperty("blog_id")
	public int getBlogId() {
		Integer value = (Integer)attributes.get("blog_id");
		return value != null ? value : 0;
	}
	@JsonProperty("blog_id")
	public void setBlogId(int _blog_id) {
		attributes.put("blog_id", _blog_id);
	}

	@JsonProperty("article_id")
	public int getArticleId() {
		Integer value = (Integer)attributes.get("article_id");
		return value != null ? value : 0;
	}
	@JsonProperty("article_id")
	public void setArticleId(int _article_id) {
		attributes.put("article_id", _article_id);
	}

	@JsonProperty("ip")
	public String getIp() {
		return (String)attributes.get("ip");
	}
	@JsonProperty("ip")
	public void setIp(String _ip) {
		attributes.put("ip", _ip);
	}

	@JsonProperty("published_at")
	public String getPublishedAt() {
		return (String)attributes.get("published_at");
	}
	@JsonProperty("published_at")
	public void setPublishedAt(String _published_at) {
		attributes.put("published_at", _published_at);
	}

	@JsonProperty("user_agent")
	public String getUserAgent() {
		return (String)attributes.get("user_agent");
	}
	@JsonProperty("user_agent")
	public void setUserAgent(String _user_agent) {
		attributes.put("user_agent", _user_agent);
	}

	@JsonProperty("status")
	public String getStatus() {
		return (String)attributes.get("status");
	}
	@JsonProperty("status")
	public void setStatus(String _status) {
		attributes.put("status", _status);
	}

	@JsonProperty("email")
	public String getEmail() {
		return (String)attributes.get("email");
	}
	@JsonProperty("email")
	public void setEmail(String _email) {
		attributes.put("email", _email);
	}

}
