/**
* DO NOT MODIFY THIS CODE
* 
* Place all of your changes in Comment.java
* 
* It has been machine generated from fixtures and your changes will be
* lost if anything new needs to be added to the API. 
**/
// Last Generated: 2011-08-26T10:00:59-04:00
package com.shopify.api.resources;

import java.util.List;
import org.codehaus.jackson.annotate.JsonProperty;

/**
* This code has been machine generated by processing the single entry
* fixtures found from the Shopify API Documentation
*/
  
public class MGComment extends ShopifyResource {

	@JsonProperty("body_html")
	private String _body_html;
	public String getBodyHtml(){ return _body_html;}
	public void setBodyHtml(String _body_html){this._body_html = _body_html;}

	@JsonProperty("author")
	private String _author;
	public String getAuthor(){ return _author;}
	public void setAuthor(String _author){this._author = _author;}

	@JsonProperty("body")
	private String _body;
	public String getBody(){ return _body;}
	public void setBody(String _body){this._body = _body;}

	@JsonProperty("blog_id")
	private int _blog_id;
	public int getBlogId(){ return _blog_id;}
	public void setBlogId(int _blog_id){this._blog_id = _blog_id;}

	@JsonProperty("article_id")
	private int _article_id;
	public int getArticleId(){ return _article_id;}
	public void setArticleId(int _article_id){this._article_id = _article_id;}

	@JsonProperty("ip")
	private String _ip;
	public String getIp(){ return _ip;}
	public void setIp(String _ip){this._ip = _ip;}

	@JsonProperty("published_at")
	private String _published_at;
	public String getPublishedAt(){ return _published_at;}
	public void setPublishedAt(String _published_at){this._published_at = _published_at;}

	@JsonProperty("user_agent")
	private String _user_agent;
	public String getUserAgent(){ return _user_agent;}
	public void setUserAgent(String _user_agent){this._user_agent = _user_agent;}

	@JsonProperty("status")
	private String _status;
	public String getStatus(){ return _status;}
	public void setStatus(String _status){this._status = _status;}

	@JsonProperty("email")
	private String _email;
	public String getEmail(){ return _email;}
	public void setEmail(String _email){this._email = _email;}

}