/**
* DO NOT MODIFY THIS CODE
* 
* Place all of your changes in Country.java
* 
* It has been machine generated from fixtures and your changes will be
* lost if anything new needs to be added to the API. 
**/
// Last Generated: 2011-08-25T23:19:06-04:00
package com.shopify.api.resources;

import org.codehaus.jackson.annotate.JsonProperty;

/**
* This code has been machine generated by processing the single entry
* fixtures found from the Shopify API Documentation
*/
  
public class MGCountry extends ShopifyResource {

	@JsonProperty("name")
	private String _name;
	public String getName(){ return _name;}
	public void setName(String _name){_name = this._name;}

	@JsonProperty("tax")
	private float _tax;
	public float getTax(){ return _tax;}
	public void setTax(float _tax){_tax = this._tax;}

	@JsonProperty("code")
	private String _code;
	public String getCode(){ return _code;}
	public void setCode(String _code){_code = this._code;}

}