/**
* DO NOT MODIFY THIS CODE
* 
* Place all of your changes in Collect.java
* 
* It has been machine generated from fixtures and your changes will be
* lost if anything new needs to be added to the API. 
**/
// Last Generated: 2011-08-25T16:56:47-04:00
package com.shopify.api.resources;

import org.codehaus.jackson.annotate.JsonProperty;

/**
* This code has been machine generated by processing the single entry
* fixtures found from the Shopify API Documentation
*/
  
public class MGCollect extends ShopifyResource {

	@JsonProperty("position")
	private int _position;
	public int getPosition(){ return _position;}
	public void setPosition(int newposition){_position = newposition;}

	@JsonProperty("product_id")
	private int _product_id;
	public int getProduct_id(){ return _product_id;}
	public void setProduct_id(int newproduct_id){_product_id = newproduct_id;}

	@JsonProperty("featured")
	private boolean _featured;
	public boolean getFeatured(){ return _featured;}
	public void setFeatured(boolean newfeatured){_featured = newfeatured;}

	@JsonProperty("collection_id")
	private int _collection_id;
	public int getCollection_id(){ return _collection_id;}
	public void setCollection_id(int newcollection_id){_collection_id = newcollection_id;}

}