/**
 * DO NOT MODIFY THIS CODE
 *
 * Place all of your changes in Event.java
 *
 * It has been machine generated from fixtures and your changes will be
 * lost if anything new needs to be added to the API.
 **/
// Last Generated: 2011-09-26T15:53:49-04:00
package com.shopify.api.resources;

import java.util.List;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * This code has been machine generated by processing the single entry
 * fixtures found from the Shopify API Documentation
 */

public class MGEvent extends ShopifyResource {

	@JsonProperty("body")
	public String getBody() {
		return (String)getAttribute("body");
	}
	@JsonProperty("body")
	public void setBody(String _body) {
		setAttribute("body", _body);
	}

	@JsonProperty("message")
	public String getMessage() {
		return (String)getAttribute("message");
	}
	@JsonProperty("message")
	public void setMessage(String _message) {
		setAttribute("message", _message);
	}

	@JsonProperty("subject_id")
	public int getSubjectId() {
		Integer value = (Integer)getAttribute("subject_id");
		return value != null ? value : 0;
	}
	@JsonProperty("subject_id")
	public void setSubjectId(int _subject_id) {
		setAttribute("subject_id", _subject_id);
	}

	@JsonProperty("subject_type")
	public String getSubjectType() {
		return (String)getAttribute("subject_type");
	}
	@JsonProperty("subject_type")
	public void setSubjectType(String _subject_type) {
		setAttribute("subject_type", _subject_type);
	}

	@JsonProperty("verb")
	public String getVerb() {
		return (String)getAttribute("verb");
	}
	@JsonProperty("verb")
	public void setVerb(String _verb) {
		setAttribute("verb", _verb);
	}

}
