/**
* DO NOT MODIFY THIS CODE
* 
* Place all of your changes in Fulfillment.java
* 
* It has been machine generated from fixtures and your changes will be
* lost if anything new needs to be added to the API. 
**/
// Last Generated: 2011-08-25T23:19:06-04:00
package com.shopify.api.resources;

import org.codehaus.jackson.annotate.JsonProperty;

/**
* This code has been machine generated by processing the single entry
* fixtures found from the Shopify API Documentation
*/
  
public class MGFulfillment extends ShopifyResource {

	// TODO: line_items is a hash or array
	/* [{"name":"IPod Nano - 8gb - green","price":"199.00","product_id":632910392,"quantity":1,"requires_shipping":true,"title":"IPod Nano - 8gb","id":466157049,"grams":200,"sku":"IPOD2008GREEN","fulfillment_status":null,"variant_title":"green","vendor":null,"fulfillment_service":"manual","variant_id":39072856}] */

	@JsonProperty("tracking_company")
	private String _tracking_company;
	public String getTrackingCompany(){ return _tracking_company;}
	public void setTrackingCompany(String _tracking_company){_tracking_company = this._tracking_company;}

	@JsonProperty("order_id")
	private int _order_id;
	public int getOrderId(){ return _order_id;}
	public void setOrderId(int _order_id){_order_id = this._order_id;}

	@JsonProperty("tracking_number")
	private String _tracking_number;
	public String getTrackingNumber(){ return _tracking_number;}
	public void setTrackingNumber(String _tracking_number){_tracking_number = this._tracking_number;}

	// TODO: receipt is a hash or array
	/* {"testcase":true,"authorization":"123456"} */

	@JsonProperty("status")
	private String _status;
	public String getStatus(){ return _status;}
	public void setStatus(String _status){_status = this._status;}

}