/**
* DO NOT MODIFY THIS CODE
* 
* Place all of your changes in Metafield.java
* 
* It has been machine generated from fixtures and your changes will be
* lost if anything new needs to be added to the API. 
**/
// Last Generated: 2011-08-25T16:56:47-04:00
package com.shopify.api.resources;

import org.codehaus.jackson.annotate.JsonProperty;

/**
* This code has been machine generated by processing the single entry
* fixtures found from the Shopify API Documentation
*/
  
public class MGMetafield extends ShopifyResource {

	@JsonProperty("namespace")
	private String _namespace;
	public String getNamespace(){ return _namespace;}
	public void setNamespace(String newnamespace){_namespace = newnamespace;}

	@JsonProperty("value")
	private String _value;
	public String getValue(){ return _value;}
	public void setValue(String newvalue){_value = newvalue;}

	@JsonProperty("description")
	private String _description;
	public String getDescription(){ return _description;}
	public void setDescription(String newdescription){_description = newdescription;}

	@JsonProperty("key")
	private String _key;
	public String getKey(){ return _key;}
	public void setKey(String newkey){_key = newkey;}

	@JsonProperty("value_type")
	private String _value_type;
	public String getValue_type(){ return _value_type;}
	public void setValue_type(String newvalue_type){_value_type = newvalue_type;}

}