/**
 * DO NOT MODIFY THIS CODE
 *
 * Place all of your changes in Metafield.java
 *
 * It has been machine generated from fixtures and your changes will be
 * lost if anything new needs to be added to the API.
 **/
// Last Generated: 2011-09-01T17:54:50-04:00
package com.shopify.api.resources;

import java.util.List;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * This code has been machine generated by processing the single entry
 * fixtures found from the Shopify API Documentation
 */

public class MGMetafield extends ShopifyResource {

	@JsonProperty("namespace")
	private String _namespace;
	@JsonProperty("namespace")
	public String getNamespace(){ return _namespace;}
	@JsonProperty("namespace")
	public void setNamespace(String _namespace){this._namespace = _namespace;}

	@JsonProperty("value")
	private String _value;
	@JsonProperty("value")
	public String getValue(){ return _value;}
	@JsonProperty("value")
	public void setValue(String _value){this._value = _value;}

	@JsonProperty("description")
	private String _description;
	@JsonProperty("description")
	public String getDescription(){ return _description;}
	@JsonProperty("description")
	public void setDescription(String _description){this._description = _description;}

	@JsonProperty("key")
	private String _key;
	@JsonProperty("key")
	public String getKey(){ return _key;}
	@JsonProperty("key")
	public void setKey(String _key){this._key = _key;}

	@JsonProperty("value_type")
	private String _value_type;
	@JsonProperty("value_type")
	public String getValueType(){ return _value_type;}
	@JsonProperty("value_type")
	public void setValueType(String _value_type){this._value_type = _value_type;}

}
