/**
* DO NOT MODIFY THIS CODE
* 
* Place all of your changes in Page.java
* 
* It has been machine generated from fixtures and your changes will be
* lost if anything new needs to be added to the API. 
**/
// Last Generated: 2011-08-25T16:56:47-04:00
package com.shopify.api.resources;

import org.codehaus.jackson.annotate.JsonProperty;

/**
* This code has been machine generated by processing the single entry
* fixtures found from the Shopify API Documentation
*/
  
public class MGPage extends ShopifyResource {

	@JsonProperty("body_html")
	private String _body_html;
	public String getBody_html(){ return _body_html;}
	public void setBody_html(String newbody_html){_body_html = newbody_html;}

	@JsonProperty("handle")
	private String _handle;
	public String getHandle(){ return _handle;}
	public void setHandle(String newhandle){_handle = newhandle;}

	@JsonProperty("author")
	private String _author;
	public String getAuthor(){ return _author;}
	public void setAuthor(String newauthor){_author = newauthor;}

	@JsonProperty("template_suffix")
	private String _template_suffix;
	public String getTemplate_suffix(){ return _template_suffix;}
	public void setTemplate_suffix(String newtemplate_suffix){_template_suffix = newtemplate_suffix;}

	@JsonProperty("title")
	private String _title;
	public String getTitle(){ return _title;}
	public void setTitle(String newtitle){_title = newtitle;}

	@JsonProperty("shop_id")
	private int _shop_id;
	public int getShop_id(){ return _shop_id;}
	public void setShop_id(int newshop_id){_shop_id = newshop_id;}

	@JsonProperty("published_at")
	private String _published_at;
	public String getPublished_at(){ return _published_at;}
	public void setPublished_at(String newpublished_at){_published_at = newpublished_at;}

}