/**
 * DO NOT MODIFY THIS CODE
 *
 * Place all of your changes in Page.java
 *
 * It has been machine generated from fixtures and your changes will be
 * lost if anything new needs to be added to the API.
 **/
// Last Generated: 2011-09-26T15:53:49-04:00
package com.shopify.api.resources;

import java.util.List;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * This code has been machine generated by processing the single entry
 * fixtures found from the Shopify API Documentation
 */

public class MGPage extends ShopifyResource {

	@JsonProperty("author")
	public String getAuthor() {
		return (String)getAttribute("author");
	}
	@JsonProperty("author")
	public void setAuthor(String _author) {
		setAttribute("author", _author);
	}

	@JsonProperty("body_html")
	public String getBodyHtml() {
		return (String)getAttribute("body_html");
	}
	@JsonProperty("body_html")
	public void setBodyHtml(String _body_html) {
		setAttribute("body_html", _body_html);
	}

	@JsonProperty("handle")
	public String getHandle() {
		return (String)getAttribute("handle");
	}
	@JsonProperty("handle")
	public void setHandle(String _handle) {
		setAttribute("handle", _handle);
	}

	@JsonProperty("published_at")
	public String getPublishedAt() {
		return (String)getAttribute("published_at");
	}
	@JsonProperty("published_at")
	public void setPublishedAt(String _published_at) {
		setAttribute("published_at", _published_at);
	}

	@JsonProperty("shop_id")
	public int getShopId() {
		Integer value = (Integer)getAttribute("shop_id");
		return value != null ? value : 0;
	}
	@JsonProperty("shop_id")
	public void setShopId(int _shop_id) {
		setAttribute("shop_id", _shop_id);
	}

	@JsonProperty("template_suffix")
	public String getTemplateSuffix() {
		return (String)getAttribute("template_suffix");
	}
	@JsonProperty("template_suffix")
	public void setTemplateSuffix(String _template_suffix) {
		setAttribute("template_suffix", _template_suffix);
	}

	@JsonProperty("title")
	public String getTitle() {
		return (String)getAttribute("title");
	}
	@JsonProperty("title")
	public void setTitle(String _title) {
		setAttribute("title", _title);
	}

}
