/**
* DO NOT MODIFY THIS CODE
* 
* Place all of your changes in ProductImage.java
* 
* It has been machine generated from fixtures and your changes will be
* lost if anything new needs to be added to the API. 
**/
// Last Generated: 2011-08-25T16:56:47-04:00
package com.shopify.api.resources;

import org.codehaus.jackson.annotate.JsonProperty;

/**
* This code has been machine generated by processing the single entry
* fixtures found from the Shopify API Documentation
*/
  
public class MGProductImage extends ShopifyResource {

	@JsonProperty("position")
	private int _position;
	public int getPosition(){ return _position;}
	public void setPosition(int newposition){_position = newposition;}

	@JsonProperty("product_id")
	private int _product_id;
	public int getProduct_id(){ return _product_id;}
	public void setProduct_id(int newproduct_id){_product_id = newproduct_id;}

	@JsonProperty("src")
	private String _src;
	public String getSrc(){ return _src;}
	public void setSrc(String newsrc){_src = newsrc;}

}