/**
 * DO NOT MODIFY THIS CODE
 *
 * Place all of your changes in Province.java
 *
 * It has been machine generated from fixtures and your changes will be
 * lost if anything new needs to be added to the API.
 **/
// Last Generated: 2011-09-12T22:14:03-04:00
package com.shopify.api.resources;

import java.util.List;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * This code has been machine generated by processing the single entry
 * fixtures found from the Shopify API Documentation
 */

public class MGProvince extends ShopifyResource {

	@JsonProperty("name")
	public String getName() {
		return (String)attributes.get("name");
	}
	@JsonProperty("name")
	public void setName(String _name) {
		attributes.put("name", _name);
	}

	@JsonProperty("tax")
	public double getTax() {
		Double value = (Double)attributes.get("tax");
		return value != null ? value : 0.0;
	}
	@JsonProperty("tax")
	public void setTax(double _tax) {
		attributes.put("tax", _tax);
	}

	@JsonProperty("code")
	public String getCode() {
		return (String)attributes.get("code");
	}
	@JsonProperty("code")
	public void setCode(String _code) {
		attributes.put("code", _code);
	}

	@JsonProperty("tax_name")
	public String getTaxName() {
		return (String)attributes.get("tax_name");
	}
	@JsonProperty("tax_name")
	public void setTaxName(String _tax_name) {
		attributes.put("tax_name", _tax_name);
	}

	@JsonProperty("tax_type")
	public String getTaxType() {
		return (String)attributes.get("tax_type");
	}
	@JsonProperty("tax_type")
	public void setTaxType(String _tax_type) {
		attributes.put("tax_type", _tax_type);
	}

}
