/**
* DO NOT MODIFY THIS CODE
* 
* Place all of your changes in Province.java
* 
* It has been machine generated from fixtures and your changes will be
* lost if anything new needs to be added to the API. 
**/
// Last Generated: 2011-08-25T16:56:47-04:00
package com.shopify.api.resources;

import org.codehaus.jackson.annotate.JsonProperty;

/**
* This code has been machine generated by processing the single entry
* fixtures found from the Shopify API Documentation
*/
  
public class MGProvince extends ShopifyResource {

	@JsonProperty("name")
	private String _name;
	public String getName(){ return _name;}
	public void setName(String newname){_name = newname;}

	@JsonProperty("tax")
	private float _tax;
	public float getTax(){ return _tax;}
	public void setTax(float newtax){_tax = newtax;}

	@JsonProperty("code")
	private String _code;
	public String getCode(){ return _code;}
	public void setCode(String newcode){_code = newcode;}

	@JsonProperty("tax_name")
	private String _tax_name;
	public String getTax_name(){ return _tax_name;}
	public void setTax_name(String newtax_name){_tax_name = newtax_name;}

	@JsonProperty("tax_type")
	private String _tax_type;
	public String getTax_type(){ return _tax_type;}
	public void setTax_type(String newtax_type){_tax_type = newtax_type;}

}