/**
 * DO NOT MODIFY THIS CODE
 *
 * Place all of your changes in Receipt.java
 *
 * It has been machine generated from fixtures and your changes will be
 * lost if anything new needs to be added to the API.
 **/
// Last Generated: 2011-09-26T15:53:49-04:00
package com.shopify.api.resources;

import java.util.List;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * This code has been machine generated by processing the single entry
 * fixtures found from the Shopify API Documentation
 */

public class MGReceipt extends ShopifyResource {

	@JsonProperty("authorization")
	public String getAuthorization() {
		return (String)getAttribute("authorization");
	}
	@JsonProperty("authorization")
	public void setAuthorization(String _authorization) {
		setAttribute("authorization", _authorization);
	}

	@JsonProperty("testcase")
	public boolean getTestcase() {
		Boolean value = (Boolean)getAttribute("testcase");
		return value != null ? value : false;
	}
	@JsonProperty("testcase")
	public void setTestcase(boolean _testcase) {
		setAttribute("testcase", _testcase);
	}

}
