/**
 * DO NOT MODIFY THIS CODE
 *
 * Place all of your changes in Redirect.java
 *
 * It has been machine generated from fixtures and your changes will be
 * lost if anything new needs to be added to the API. 
 **/
// Last Generated: 2011-08-31T09:06:23-04:00
package com.shopify.api.resources;

import java.util.List;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * This code has been machine generated by processing the single entry
 * fixtures found from the Shopify API Documentation
 */

public class MGRedirect extends ShopifyResource {

	@JsonProperty("path")
	private String _path;
	@JsonProperty("path")
	public String getPath(){ return _path;}
	@JsonProperty("path")
	public void setPath(String _path){this._path = _path;}

	@JsonProperty("target")
	private String _target;
	@JsonProperty("target")
	public String getTarget(){ return _target;}
	@JsonProperty("target")
	public void setTarget(String _target){this._target = _target;}

}