/**
* DO NOT MODIFY THIS CODE
* 
* Place all of your changes in Redirect.java
* 
* It has been machine generated from fixtures and your changes will be
* lost if anything new needs to be added to the API. 
**/
// Last Generated: 2011-08-25T16:56:47-04:00
package com.shopify.api.resources;

import org.codehaus.jackson.annotate.JsonProperty;

/**
* This code has been machine generated by processing the single entry
* fixtures found from the Shopify API Documentation
*/
  
public class MGRedirect extends ShopifyResource {

	@JsonProperty("path")
	private String _path;
	public String getPath(){ return _path;}
	public void setPath(String newpath){_path = newpath;}

	@JsonProperty("target")
	private String _target;
	public String getTarget(){ return _target;}
	public void setTarget(String newtarget){_target = newtarget;}

}