/**
 * DO NOT MODIFY THIS CODE
 *
 * Place all of your changes in Rule.java
 *
 * It has been machine generated from fixtures and your changes will be
 * lost if anything new needs to be added to the API.
 **/
// Last Generated: 2011-09-26T15:53:49-04:00
package com.shopify.api.resources;

import java.util.List;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * This code has been machine generated by processing the single entry
 * fixtures found from the Shopify API Documentation
 */

public class MGRule extends ShopifyResource {

	@JsonProperty("column")
	public String getColumn() {
		return (String)getAttribute("column");
	}
	@JsonProperty("column")
	public void setColumn(String _column) {
		setAttribute("column", _column);
	}

	@JsonProperty("condition")
	public String getCondition() {
		return (String)getAttribute("condition");
	}
	@JsonProperty("condition")
	public void setCondition(String _condition) {
		setAttribute("condition", _condition);
	}

	@JsonProperty("relation")
	public String getRelation() {
		return (String)getAttribute("relation");
	}
	@JsonProperty("relation")
	public void setRelation(String _relation) {
		setAttribute("relation", _relation);
	}

}
