/**
* DO NOT MODIFY THIS CODE
* 
* Place all of your changes in ShippingAddress.java
* 
* It has been machine generated from fixtures and your changes will be
* lost if anything new needs to be added to the API. 
**/
// Last Generated: 2011-08-25T23:29:48-04:00
package com.shopify.api.resources;

import org.codehaus.jackson.annotate.JsonProperty;

/**
* This code has been machine generated by processing the single entry
* fixtures found from the Shopify API Documentation
*/
  
public class MGShippingAddress extends ShopifyResource {

	@JsonProperty("company")
	private String _company;
	public String getCompany(){ return _company;}
	public void setCompany(String _company){_company = this._company;}

	@JsonProperty("city")
	private String _city;
	public String getCity(){ return _city;}
	public void setCity(String _city){_city = this._city;}

	@JsonProperty("address1")
	private String _address1;
	public String getAddress1(){ return _address1;}
	public void setAddress1(String _address1){_address1 = this._address1;}

	@JsonProperty("name")
	private String _name;
	public String getName(){ return _name;}
	public void setName(String _name){_name = this._name;}

	@JsonProperty("zip")
	private String _zip;
	public String getZip(){ return _zip;}
	public void setZip(String _zip){_zip = this._zip;}

	@JsonProperty("latitude")
	private String _latitude;
	public String getLatitude(){ return _latitude;}
	public void setLatitude(String _latitude){_latitude = this._latitude;}

	@JsonProperty("address2")
	private String _address2;
	public String getAddress2(){ return _address2;}
	public void setAddress2(String _address2){_address2 = this._address2;}

	@JsonProperty("country")
	private String _country;
	public String getCountry(){ return _country;}
	public void setCountry(String _country){_country = this._country;}

	@JsonProperty("country_code")
	private String _country_code;
	public String getCountryCode(){ return _country_code;}
	public void setCountryCode(String _country_code){_country_code = this._country_code;}

	@JsonProperty("province_code")
	private String _province_code;
	public String getProvinceCode(){ return _province_code;}
	public void setProvinceCode(String _province_code){_province_code = this._province_code;}

	@JsonProperty("phone")
	private String _phone;
	public String getPhone(){ return _phone;}
	public void setPhone(String _phone){_phone = this._phone;}

	@JsonProperty("last_name")
	private String _last_name;
	public String getLastName(){ return _last_name;}
	public void setLastName(String _last_name){_last_name = this._last_name;}

	@JsonProperty("longitude")
	private String _longitude;
	public String getLongitude(){ return _longitude;}
	public void setLongitude(String _longitude){_longitude = this._longitude;}

	@JsonProperty("province")
	private String _province;
	public String getProvince(){ return _province;}
	public void setProvince(String _province){_province = this._province;}

	@JsonProperty("first_name")
	private String _first_name;
	public String getFirstName(){ return _first_name;}
	public void setFirstName(String _first_name){_first_name = this._first_name;}

}