/**
 * DO NOT MODIFY THIS CODE
 *
 * Place all of your changes in TaxLine.java
 *
 * It has been machine generated from fixtures and your changes will be
 * lost if anything new needs to be added to the API.
 **/
// Last Generated: 2011-09-12T22:14:03-04:00
package com.shopify.api.resources;

import java.util.List;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * This code has been machine generated by processing the single entry
 * fixtures found from the Shopify API Documentation
 */

public class MGTaxLine extends ShopifyResource {

	@JsonProperty("price")
	public String getPrice() {
		return (String)attributes.get("price");
	}
	@JsonProperty("price")
	public void setPrice(String _price) {
		attributes.put("price", _price);
	}

	@JsonProperty("title")
	public String getTitle() {
		return (String)attributes.get("title");
	}
	@JsonProperty("title")
	public void setTitle(String _title) {
		attributes.put("title", _title);
	}

	@JsonProperty("rate")
	public double getRate() {
		Double value = (Double)attributes.get("rate");
		return value != null ? value : 0.0;
	}
	@JsonProperty("rate")
	public void setRate(double _rate) {
		attributes.put("rate", _rate);
	}

}
