/**
 * DO NOT MODIFY THIS CODE
 *
 * Place all of your changes in Transactions.java
 *
 * It has been machine generated from fixtures and your changes will be
 * lost if anything new needs to be added to the API. 
 **/
// Last Generated: 2011-08-31T09:06:23-04:00
package com.shopify.api.resources;

import java.util.List;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * This code has been machine generated by processing the single entry
 * fixtures found from the Shopify API Documentation
 */

public class MGTransactions extends ShopifyResource {

	@JsonProperty("kind")
	private String _kind;
	@JsonProperty("kind")
	public String getKind(){ return _kind;}
	@JsonProperty("kind")
	public void setKind(String _kind){this._kind = _kind;}

	@JsonProperty("order_id")
	private int _order_id;
	@JsonProperty("order_id")
	public int getOrderId(){ return _order_id;}
	@JsonProperty("order_id")
	public void setOrderId(int _order_id){this._order_id = _order_id;}

	@JsonProperty("amount")
	private String _amount;
	@JsonProperty("amount")
	public String getAmount(){ return _amount;}
	@JsonProperty("amount")
	public void setAmount(String _amount){this._amount = _amount;}

	@JsonProperty("authorization")
	private String _authorization;
	@JsonProperty("authorization")
	public String getAuthorization(){ return _authorization;}
	@JsonProperty("authorization")
	public void setAuthorization(String _authorization){this._authorization = _authorization;}

	@JsonProperty("receipt")
	private Receipt _receipt;
	@JsonProperty("receipt")
	public Receipt getReceipt(){ return _receipt;}
	@JsonProperty("receipt")
	public void setReceipt(Receipt _receipt){this._receipt = _receipt;}

	@JsonProperty("status")
	private String _status;
	@JsonProperty("status")
	public String getStatus(){ return _status;}
	@JsonProperty("status")
	public void setStatus(String _status){this._status = _status;}

}