/**
 * DO NOT MODIFY THIS CODE
 *
 * Place all of your changes in Transaction.java
 *
 * It has been machine generated from fixtures and your changes will be
 * lost if anything new needs to be added to the API.
 **/
// Last Generated: 2011-09-26T15:53:49-04:00
package com.shopify.api.resources;

import java.util.List;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * This code has been machine generated by processing the single entry
 * fixtures found from the Shopify API Documentation
 */

public class MGTransaction extends ShopifyResource {

	@JsonProperty("amount")
	public String getAmount() {
		return (String)getAttribute("amount");
	}
	@JsonProperty("amount")
	public void setAmount(String _amount) {
		setAttribute("amount", _amount);
	}

	@JsonProperty("authorization")
	public String getAuthorization() {
		return (String)getAttribute("authorization");
	}
	@JsonProperty("authorization")
	public void setAuthorization(String _authorization) {
		setAttribute("authorization", _authorization);
	}

	@JsonProperty("kind")
	public String getKind() {
		return (String)getAttribute("kind");
	}
	@JsonProperty("kind")
	public void setKind(String _kind) {
		setAttribute("kind", _kind);
	}

	@JsonProperty("order_id")
	public int getOrderId() {
		Integer value = (Integer)getAttribute("order_id");
		return value != null ? value : 0;
	}
	@JsonProperty("order_id")
	public void setOrderId(int _order_id) {
		setAttribute("order_id", _order_id);
	}

	@JsonProperty("receipt")
	public Receipt getReceipt() {
		return (Receipt)getAttribute("receipt");
	}
	@JsonProperty("receipt")
	public void setReceipt(Receipt _receipt) {
		setAttribute("receipt", _receipt);
	}

	@JsonProperty("status")
	public String getStatus() {
		return (String)getAttribute("status");
	}
	@JsonProperty("status")
	public void setStatus(String _status) {
		setAttribute("status", _status);
	}

}
