/**
 * DO NOT MODIFY THIS CODE
 *
 * Place all of your changes in Webhook.java
 *
 * It has been machine generated from fixtures and your changes will be
 * lost if anything new needs to be added to the API.
 **/
// Last Generated: 2011-09-12T22:14:03-04:00
package com.shopify.api.resources;

import java.util.List;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * This code has been machine generated by processing the single entry
 * fixtures found from the Shopify API Documentation
 */

public class MGWebhook extends ShopifyResource {

	@JsonProperty("address")
	public String getAddress() {
		return (String)attributes.get("address");
	}
	@JsonProperty("address")
	public void setAddress(String _address) {
		attributes.put("address", _address);
	}

	@JsonProperty("format")
	public String getFormat() {
		return (String)attributes.get("format");
	}
	@JsonProperty("format")
	public void setFormat(String _format) {
		attributes.put("format", _format);
	}

	@JsonProperty("topic")
	public String getTopic() {
		return (String)attributes.get("topic");
	}
	@JsonProperty("topic")
	public void setTopic(String _topic) {
		attributes.put("topic", _topic);
	}

}
